'use client';

import { useState, useEffect, useRef } from 'react';
import {
  User,
  MapPin,
  Package,
  LifeBuoy,
  LogOut,
  Camera,
  Loader2
} from 'lucide-react';
import Image from 'next/image';
import { dispatchAuthChange } from '@/lib/authEvents';
import ImageCropModal from '@/components/UI/ImageCropModal';
import ProfileTab from '@/components/WebSite/Profile/ProfileTab';
import AddressBook from '@/components/WebSite/Profile/AddressBook';
import OrderHistory from '@/components/WebSite/Profile/OrderHistory';
import SupportTickets from '@/components/WebSite/Profile/SupportTickets';
import Reveal from '@/components/WebSite/Shared/Reveal';
import LogoutConfirmModal from '@/components/WebSite/Shared/LogoutConfirmModal';
// import Notifications from '@/components/WebSite/Profile/Notifications';
import type { UserProfile } from '@/components/WebSite/Profile/types';
import { showSuccessToast, showErrorToast } from '@/lib/toast-utils';
import { userProfileService } from '@/services/userProfileService';
import { userAuthService } from '@/services/userAuthService';
import { useRouter } from 'next/navigation';

/**
 * My Account.
 *
 * A merge of two lines of work. Everything behavioural comes from main and is
 * unchanged: the phone/WhatsApp split-and-join around country codes, the
 * crop-then-upload photo flow, and syncStoredImage, which mirrors a new
 * picture into the stored auth session so the header avatar updates instantly
 * instead of waiting for a reload.
 *
 * What changed here is presentation:
 *
 *  · The palette. The page was slate grey with a bootstrap-blue notice while
 *    the storefront is linen, cream and oxblood, so the two did not look like
 *    the same product.
 *
 *  · The edit controls left the sidebar for the card they act on. They used
 *    to sit in the left rail on every tab, including Orders and Support where
 *    pressing Edit put the profile into an edit mode nothing on screen showed.
 *
 *  · The sidebar identity card is a centred stack and shows the join date,
 *    which was already being fetched, mapped into state and then never shown.
 */

/**
 * The page ground.
 *
 * Flat #faf7f3 is the same colour as the cards, so nothing lifted off
 * anything. A woven warp texture is the obvious answer for a textile business
 * and was ruled out — the client does not want stripes, and warp threads are
 * stripes.
 *
 * So: no pattern at all. Four very large, very soft pools of warm colour,
 * placed so no two edges of the page are the same shade. Nothing repeats,
 * nothing tiles, and there is not a straight line in it — but the ground stops
 * being one colour.
 *
 * Cheap to paint: these are plain radial-gradients, not blurred elements. A
 * filter: blur() on something this size would cost a full-page repaint.
 *
 * Each stop fades to its OWN colour at zero alpha rather than to `transparent`.
 * `transparent` is rgba(0,0,0,0), so fading to it drags every midpoint toward
 * black and leaves a dirty grey halo.
 */
const PAGE_GROUND = [
  // Rose, strongest behind the header where the eye lands first.
  'radial-gradient(1400px 620px at 18% -8%, #f7e3dd 0%, rgba(247, 227, 221, 0) 64%)',
  // Warm gold, top right, so the top edge is not one uniform tone.
  'radial-gradient(1000px 560px at 96% 2%, #fdf0df 0%, rgba(253, 240, 223, 0) 60%)',
  // Sand, low and right — the corner that reads as empty when content is short.
  'radial-gradient(1100px 900px at 84% 96%, #f2e6d8 0%, rgba(242, 230, 216, 0) 66%)',
  // A cooler linen counterweight bottom left, so the page is not all one hue.
  'radial-gradient(900px 700px at 2% 90%, #f5efe6 0%, rgba(245, 239, 230, 0) 62%)',
  '#faf7f3',
].join(', ');

/**
 * Fine grain over the top.
 *
 * Four soft gradients still look like digital paint; grain is what makes a
 * surface read as a surface. Generated by feTurbulence in an inline SVG, so it
 * is one data URI with no network request and no image asset to ship. Random
 * noise, not a pattern — nothing in it lines up or repeats visibly at 4%.
 */
const GRAIN =
  "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160'%3E%3Cfilter id='g'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='160' height='160' filter='url(%23g)'/%3E%3C/svg%3E\")";

/**
 * Both layers, behind everything, inert to the pointer.
 *
 * Contrast where it matters: the header type sits over the rose pool at
 * roughly #f7e3dd, where the #c41617 eyebrow measures 5.1:1, #5f5550 body text
 * 6.1:1 and the #1a1a1a heading 15.4:1.
 */
function PageGround() {
  return (
    <>
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0"
        style={{ background: PAGE_GROUND }}
      />
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 opacity-[0.04] mix-blend-multiply"
        style={{ backgroundImage: GRAIN, backgroundSize: '160px 160px' }}
      />
    </>
  );
}

const Profile = () => {
  const router = useRouter();
  const [isEditing, setIsEditing] = useState(false);
  const [activeTab, setActiveTab] = useState('profile');
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [showLogoutConfirm, setShowLogoutConfirm] = useState(false);
  const [isLoggingOut, setIsLoggingOut] = useState(false);

  // User data with placeholders
  const [userProfile, setUserProfile] = useState<UserProfile>({
    id: 'user_123',
    title: '',
    firstName: '',
    middleName: '',
    lastName: '',
    email: '',
    phone: '',
    phoneCode: '+91',
    whatsapp: '',
    whatsappCode: '+91',
    gender: 'male',
    joinDate: new Date().toISOString().split('T')[0],
    preferences: {
      newsletter: false,
      smsNotifications: false,
      emailNotifications: false
    }
  });

  const [editedProfile, setEditedProfile] = useState<UserProfile>(userProfile);
  const [isUploadingPhoto, setIsUploadingPhoto] = useState(false);
  const [cropSrc, setCropSrc] = useState<string | null>(null);
  const [cropFileName, setCropFileName] = useState('profile');
  const fileInputRef = useRef<HTMLInputElement>(null);

  const loadUserProfile = async () => {
    try {
      setIsLoading(true);
      const response = await userProfileService.getProfile();

      if (response.success && response.data) {
        const userData = response.data;

        // Split name into first and last name
        const nameParts = userData.name?.split(' ') || ['', ''];
        const firstName = nameParts[0] || '';
        const lastName = nameParts.slice(1).join(' ') || '';

        // Phone / WhatsApp are stored as "+<code> <number>" — split for the UI.
        const splitPhone = (v?: string): { code: string; num: string } => {
          const s = (v || '').trim();
          if (s.startsWith('+')) {
            const sp = s.indexOf(' ');
            if (sp > 0) return { code: s.slice(0, sp), num: s.slice(sp + 1).trim() };
          }
          return { code: '+91', num: s };
        };
        const ph = splitPhone(userData.phoneNumber);
        const wa = splitPhone(userData.whatsappNumber);

        const profile: UserProfile = {
          id: userData.id,
          title: userData.title || '',
          firstName,
          middleName: userData.middleName || '',
          lastName,
          email: userData.email,
          phone: ph.num,
          phoneCode: ph.code,
          whatsapp: wa.num,
          whatsappCode: wa.code,
          image: userData.image || '',
          gender: (['male', 'female', 'other'].includes(String(userData.gender || '').toLowerCase())
            ? String(userData.gender).toLowerCase()
            : '') as UserProfile['gender'],
          joinDate: new Date(userData.createdAt).toISOString().split('T')[0],
          preferences: {
            newsletter: false,
            smsNotifications: false,
            emailNotifications: false
          }
        };

        setUserProfile(profile);
        setEditedProfile(profile);
      }
    } catch (error: any) {
      console.error('Error loading profile:', error);
      showErrorToast('Load Failed', error.message || 'Unable to load profile data');
    } finally {
      setIsLoading(false);
    }
  };

  // On mount. Declared after loadUserProfile rather than before it, so the
  // call does not reach into the temporal dead zone of a `const` defined
  // further down.
  useEffect(() => {
    loadUserProfile();
  }, []);

  const handleSave = async () => {
    try {
      setIsSaving(true);

      // Combine first and last name
      const fullName = `${editedProfile.firstName} ${editedProfile.lastName}`.trim();

      if (!fullName) {
        showErrorToast('Validation Error', 'Name is required');
        return;
      }

      const email = (editedProfile.email || '').trim();
      if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) {
        showErrorToast('Validation Error', 'Enter a valid email address');
        return;
      }

      // Profile update now only covers personal info. Addresses are managed
      // separately in the Saved Addresses tab. Phone/WhatsApp are stored with
      // their country code prefix ("+91 98765...").
      const joinPhone = (code?: string, num?: string) => {
        const n = (num || '').trim();
        return n ? `${(code || '+91').trim()} ${n}` : '';
      };
      const updateData = {
        name: fullName,
        email,
        gender: editedProfile.gender || '',
        title: editedProfile.title || '',
        middleName: editedProfile.middleName || '',
        phoneNumber: joinPhone(editedProfile.phoneCode, editedProfile.phone),
        whatsappNumber: joinPhone(editedProfile.whatsappCode, editedProfile.whatsapp),
      };

      const response = await userProfileService.updateProfile(updateData);

      if (response.success) {
        setUserProfile(editedProfile);
        setIsEditing(false);
        showSuccessToast('Profile Updated', 'Your profile has been updated successfully');
        // Reload profile to get updated data from backend
        await loadUserProfile();
      }
    } catch (error: any) {
      console.error('Error saving profile:', error);
      showErrorToast('Save Failed', error.message || 'Unable to save profile changes');
    } finally {
      setIsSaving(false);
    }
  };

  const handleCancel = () => {
    setEditedProfile(userProfile);
    setIsEditing(false);
  };

  // Mirror the new photo into the stored auth session so the header avatar
  // updates instantly (same mechanism login uses).
  const syncStoredImage = (image: string) => {
    try {
      const store = localStorage.getItem('userToken') ? localStorage : sessionStorage;
      const raw = store.getItem('userData');
      if (raw) {
        const u = JSON.parse(raw);
        u.image = image;
        store.setItem('userData', JSON.stringify(u));
      }
      dispatchAuthChange();
    } catch {
      /* non-fatal — header will pick it up on next load */
    }
  };

  const fileToDataUrl = (file: File) =>
    new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });

  // Step 1 — pick a file, then open the crop modal (upload happens after crop).
  const handleAvatarChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = ''; // allow re-selecting the same file
    if (!file) return;
    if (!file.type.startsWith('image/')) {
      showErrorToast('Invalid file', 'Please choose an image file.');
      return;
    }
    if (file.size > 8 * 1024 * 1024) {
      showErrorToast('Image too large', 'Please choose an image under 8MB.');
      return;
    }
    try {
      const dataUrl = await fileToDataUrl(file);
      setCropFileName(file.name || 'profile');
      setCropSrc(dataUrl);
    } catch {
      showErrorToast('Error', 'Could not read the selected image.');
    }
  };

  // Step 2 — receive the cropped square image and upload it.
  const handleCropped = async (file: File) => {
    setCropSrc(null);
    try {
      setIsUploadingPhoto(true);
      const dataUrl = await fileToDataUrl(file);
      const fullName = `${userProfile.firstName} ${userProfile.lastName}`.trim() || userProfile.email;
      const response = await userProfileService.updateProfile({ name: fullName, image: dataUrl });
      if (response.success) {
        const newImg = response.data?.image || '';
        setUserProfile((p) => ({ ...p, image: newImg }));
        setEditedProfile((p) => ({ ...p, image: newImg }));
        syncStoredImage(newImg);
        showSuccessToast('Photo updated', 'Your profile photo has been updated successfully.');
      }
    } catch (error: any) {
      console.error('Avatar upload error:', error);
      showErrorToast('Upload failed', error.message || 'Unable to update your photo.');
    } finally {
      setIsUploadingPhoto(false);
    }
  };

  /**
   * Confirmed logout. Sign Out opens the dialog; this only runs once the
   * customer has said yes.
   *
   * isLoggingOut keeps the dialog on screen with both buttons inert while the
   * request is in flight, rather than closing it and leaving the page looking
   * idle. The dialog is never closed here — the redirect ends the page.
   */
  const handleLogout = async () => {
    setIsLoggingOut(true);
    try {
      await userAuthService.logout();
      userAuthService.clearAuthData(); // Clear stored auth data
      showSuccessToast('Logged Out', 'You have been logged out successfully');
      router.push('/');
    } catch (error) {
      console.error('Logout error:', error);
      // Even if API call fails, clear local data
      userAuthService.clearAuthData();
      showErrorToast('Logout Failed', 'Unable to logout. Please try again.');
      router.push('/');
    }
  };

  const tabs = [
    { id: 'profile', label: 'Profile Information', icon: User },
    { id: 'addresses', label: 'Saved Addresses', icon: MapPin },
    { id: 'orders', label: 'Order History', icon: Package },
    { id: 'support', label: 'Support', icon: LifeBuoy },
  ];

  const renderProfileTab = () => (
    <ProfileTab
      editedProfile={editedProfile}
      setEditedProfile={setEditedProfile}
      isEditing={isEditing}
      isSaving={isSaving}
      onEdit={() => setIsEditing(true)}
      onSave={handleSave}
      onCancel={handleCancel}
      onGoToAddresses={() => setActiveTab('addresses')}
    />
  );

  // Initials for the avatar. Falls back to a single glyph rather than an empty
  // circle when only one name is on file.
  const initials = `${userProfile.firstName.charAt(0)}${userProfile.lastName.charAt(0)}`.toUpperCase() || 'U';

  // joinDate has always been fetched, mapped and thrown away. Rendered as
  // "March 2024" — the day is noise on an account page.
  const memberSince = (() => {
    const d = new Date(userProfile.joinDate);
    return Number.isNaN(d.getTime())
      ? null
      : d.toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
  })();

  if (isLoading) {
    /* Skeleton mirrors the page: header, sidebar identity card + nav, content
       card. Same warm ground, so nothing changes colour when the fetch lands. */
    return (
      <div className="relative min-h-[60vh] bg-[#faf7f3] py-8 font-sans">
        <PageGround />
        <div className="relative mx-auto max-w-328 px-4 sm:px-6 lg:px-8">
          <div className="mb-8 space-y-3">
            <div className="h-3 w-28 animate-pulse rounded bg-[#ece2d6]" />
            <div className="h-9 w-56 animate-pulse rounded bg-[#ece2d6]" />
            <div className="h-4 w-72 animate-pulse rounded bg-[#f3ece3]" />
          </div>
          <div className="flex flex-col gap-8 lg:flex-row">
            <div className="shrink-0 lg:w-72">
              <div className="rounded-2xl border border-[#efe4d8] bg-white p-4">
                <div className="mb-6 flex flex-col items-center gap-3">
                  <div className="h-18 w-18 animate-pulse rounded-full bg-[#ece2d6]" />
                  <div className="h-4 w-28 animate-pulse rounded bg-[#ece2d6]" />
                  <div className="h-3 w-36 animate-pulse rounded bg-[#f3ece3]" />
                </div>
                <div className="space-y-2">
                  {Array.from({ length: 5 }).map((_, i) => (
                    <div key={i} className="h-11 w-full animate-pulse rounded-xl bg-[#f3ece3]" />
                  ))}
                </div>
              </div>
            </div>
            <div className="flex-1 space-y-4 rounded-2xl border border-[#efe4d8] bg-white p-4 sm:p-6 lg:p-7">
              <div className="h-7 w-48 animate-pulse rounded bg-[#ece2d6]" />
              <div className="mt-6 grid grid-cols-1 gap-5 sm:grid-cols-2">
                {Array.from({ length: 6 }).map((_, i) => (
                  <div key={i} className="space-y-2">
                    <div className="h-3 w-24 animate-pulse rounded bg-[#f3ece3]" />
                    <div className="h-12 w-full animate-pulse rounded-xl bg-[#ece2d6]" />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="relative min-h-[60vh] bg-[#faf7f3] py-4 font-sans sm:py-6 lg:py-8">
      <PageGround />

      {/* Crop step of the photo flow, from main, called exactly as it is
          there. There is no `open` prop — a null `src` is what closes it. */}
      <ImageCropModal
        src={cropSrc}
        fileName={cropFileName}
        title="Crop profile photo"
        cropShape="round"
        onCancel={() => setCropSrc(null)}
        onCropped={handleCropped}
      />

      <div className="relative mx-auto max-w-328 px-3 sm:px-4 md:px-6 lg:px-8">
        {/* ── Page header ────────────────────────────────────────────────
            The standalone red person icon beside the title is gone. The
            avatar in the sidebar says whose account this is, and the icon was
            saying it a second time at a size that made it the loudest thing
            on the page. */}
        <Reveal className="mb-5 sm:mb-6 lg:mb-8">
          <span className="mb-2 inline-flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-[#c41617] sm:text-xs">
            <span aria-hidden className="h-px w-6 bg-[#c41617]" />
            Your account
          </span>
          <h1 className="mb-1 font-playfair text-2xl font-semibold tracking-tight text-[#1a1a1a] sm:mb-2 sm:text-3xl lg:text-4xl">
            My Account
          </h1>
          <p className="text-sm text-[#5f5550] sm:text-base">
            Manage your profile and account settings
          </p>
        </Reveal>

        <div className="flex flex-col gap-5 sm:gap-6 lg:flex-row lg:gap-8">
          {/* ── Sidebar ──────────────────────────────────────────────────── */}
          {/* Sticky from lg up. Order History runs to about 1,600px while
              this column is roughly 400px, so scrolling the orders used to
              leave a metre of empty page where the navigation had been. */}
          <Reveal className="shrink-0 lg:sticky lg:top-6 lg:w-72 lg:self-start" delay={90}>
            <div className="rounded-2xl border border-[#efe4d8] bg-white p-3 shadow-[0_10px_30px_-24px_rgba(74,50,38,0.5)] sm:p-4">
              {/* ── Identity ──────────────────────────────────────────────
                  Centred stack, and no rule inside it. A hairline between the
                  name and the email cut apart the one pair that belongs
                  together, and a big avatar top-left above two full-width
                  lines made an L that never resolved. Centring removes both,
                  and a long email wraps onto two centred lines instead of
                  breaking against a left edge.

                  No tinted panel either: #faf7f3 on white is barely a colour,
                  so all it did was draw a second frame inside a card that was
                  already a frame. */}
              <div className="mb-4 border-b border-[#f2e9df] px-2 pt-2 pb-5 text-center">
                <div className="flex flex-col items-center">
                  {/* ── Avatar ────────────────────────────────────────────
                      A button, not decoration. Opens the file picker, which
                      opens the crop modal, which uploads — the flow from main,
                      unchanged. The photograph shows when the account has one,
                      which includes every Google sign-in. Initials are the
                      fallback, not the only state. */}
                  <div className="relative shrink-0">
                    <button
                      type="button"
                      onClick={() => fileInputRef.current?.click()}
                      disabled={isUploadingPhoto}
                      aria-label={userProfile.image ? 'Change profile picture' : 'Add a profile picture'}
                      className="group relative grid h-18 w-18 place-items-center overflow-hidden rounded-full bg-linear-to-br from-[#e01a1b] to-[#7a0f10] shadow-[0_8px_18px_-8px_rgba(122,15,16,0.7)] transition-transform duration-200 hover:scale-[1.04] disabled:cursor-wait"
                    >
                      {userProfile.image ? (
                        <Image
                          src={userProfile.image}
                          alt=""
                          fill
                          sizes="72px"
                          className="object-cover"
                          // Avatars come from Cloudinary and, for Google
                          // accounts, from googleusercontent — unoptimized
                          // keeps this working without every possible avatar
                          // host being listed in next.config.
                          unoptimized
                        />
                      ) : (
                        <span aria-hidden className="font-playfair text-[23px] font-semibold text-white">
                          {initials}
                        </span>
                      )}

                      {/* Hover and keyboard focus only. On touch the tap opens
                          the picker anyway, so the overlay was a hint rather
                          than a mechanism — and a permanent scrim over your own
                          photograph is a poor trade for a hint. The aria-label
                          on the button still tells a screen reader what it does. */}
                      <span
                        aria-hidden
                        className="absolute inset-0 grid place-items-center bg-black/45 opacity-0 transition-opacity duration-200 group-hover:opacity-100 group-focus-visible:opacity-100"
                      >
                        <Camera className="h-[18px] w-[18px] text-white" />
                      </span>

                      {isUploadingPhoto && (
                        <span aria-hidden className="absolute inset-0 grid place-items-center bg-black/55">
                          <Loader2 className="h-4 w-4 animate-spin text-white" />
                        </span>
                      )}
                    </button>

                    <input
                      ref={fileInputRef}
                      type="file"
                      accept="image/*"
                      onChange={handleAvatarChange}
                      className="hidden"
                    />
                  </div>

                  <h2 className="mt-3 text-[15px] font-semibold text-[#1a1a1a]">
                    {userProfile.firstName} {userProfile.lastName}
                  </h2>

                  {/* break-words, not break-all: it breaks at the @ and the
                      dots first and only splits a run of characters when it
                      has to, so an ordinary address never ends up hyphenated
                      mid-word. #7a6d62 measures 5.0:1 on white. */}
                  <p
                    className="mt-0.5 max-w-full text-xs break-words text-[#7a6d62]"
                    title={userProfile.email}
                  >
                    {userProfile.email}
                  </p>

                  {memberSince && (
                    <p className="mt-2.5 text-[11px] font-medium uppercase tracking-[0.1em] text-[#a89a8d]">
                      Member since {memberSince}
                    </p>
                  )}
                </div>
              </div>

              <nav className="space-y-1">
                {tabs.map((tab) => {
                  const Icon = tab.icon;
                  const active = activeTab === tab.id;
                  return (
                    <button
                      key={tab.id}
                      onClick={() => setActiveTab(tab.id)}
                      aria-current={active ? 'page' : undefined}
                      className={`relative flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-[14px] font-medium transition-colors duration-200 ${active
                        ? 'bg-[#fdf3f0] text-[#7a0f10]'
                        : 'text-[#5f5550] hover:bg-[#faf7f3] hover:text-[#1a1a1a]'
                        }`}
                    >
                      {/* A bar rather than a border: a bordered active item is
                          1px wider than its neighbours, so the whole list
                          shifts as you move between tabs. */}
                      <span
                        aria-hidden
                        className={`absolute left-0 top-1/2 h-6 w-[3px] -translate-y-1/2 rounded-r-full bg-[#e01a1b] transition-opacity duration-200 ${active ? 'opacity-100' : 'opacity-0'
                          }`}
                      />
                      <Icon className={`h-[18px] w-[18px] ${active ? 'text-[#e01a1b]' : 'text-[#a89a8d]'}`} />
                      <span>{tab.label}</span>
                    </button>
                  );
                })}

                <div aria-hidden className="my-3 h-px bg-[#f2e9df]" />

                <button
                  onClick={() => setShowLogoutConfirm(true)}
                  className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-[14px] font-medium text-[#5f5550] transition-colors duration-200 hover:bg-[#fdf3f0] hover:text-[#7a0f10]"
                >
                  <LogOut className="h-[18px] w-[18px] text-[#a89a8d]" />
                  <span>Sign Out</span>
                </button>
              </nav>
            </div>
          </Reveal>

          {/* ── Main content ─────────────────────────────────────────────── */}
          <Reveal className="min-w-0 flex-1" delay={180}>
            {activeTab === 'profile' && renderProfileTab()}
            {activeTab === 'addresses' && <AddressBook />}
            {activeTab === 'orders' && <OrderHistory />}
            {activeTab === 'support' && <SupportTickets />}
          </Reveal>
        </div>
      </div>

      <LogoutConfirmModal
        open={showLogoutConfirm}
        onCancel={() => setShowLogoutConfirm(false)}
        onConfirm={handleLogout}
        isLoggingOut={isLoggingOut}
        userName={`${userProfile.firstName} ${userProfile.lastName}`.trim() || undefined}
      />
    </div>
  );
};

export default Profile;
